name: Sync Mentor Files

on:
  schedule:
    - cron: '0 4 * * *'    # Run daily at 4 AM UTC
  workflow_dispatch:        # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your own repo (where the workflow lives)
      - name: Checkout my repo
        uses: actions/checkout
        with:
          path: my-repo

      # Step 2: Checkout mentor's repo into separate folder
      - name: Checkout mentor's repo
        uses: actions/checkout
        with:
          repository: nlopatin-gd/argevorgyan-internship
          token: ${{ secrets.GITHUB_TOKEN }}
          path: mentor-repo

      # Step 3: Copy mentor files to your repo folder
      - name: Copy files from mentor to my repo
        uses: actions/upload-artifact
        with:
          name: mentor-files
          path: mentor-repo/
          
      - name: Download mentor files artifact
        uses: actions/download-artifact
        with:
          name: mentor-files
          path: my-repo/

      # Step 4: Commit & push changes
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action
        with:
          commit_message: "Sync from mentor repo"
          branch: main
          directory: my-repo