name: Sync Mentor Files

on:
  schedule:
    - cron: '0 4 * * *'    # Run daily at 4 AM UTC
  workflow_dispatch:        # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          path: my-repo

      #Checkout mentor's repo
      - name: Checkout mentor's repo
        uses: actions/checkout@v4
        with:
          repository: nlopatin-gd/argevorgyan-internship
          token: ${{ secrets.GITHUB_TOKEN }}
          path: mentor-repo

      # Copy files from mentor's repo to my repo
      - name: Copy files from mentor to my repo
        uses: actions/upload-artifact@v4
        with:
          name: mentor-files
          path: mentor-repo/
          
      - name: Download mentor files artifact
        uses: actions/download-artifact@v4
        with:
          name: mentor-files
          path: my-repo/

      # Commit & push changes
      - name: Commit and push changes
        run: |
       git config user.name "github-actions[bot]"
       git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

       git add .
       git commit -m "Synced latest changes from mentor repo" || echo "No changes to commit"
       git push origin main